<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	  <UserSecretsId>compriax-mercadopago-secrets-3919d9c8-b4c0-4dab-b5b3-aea41037300f</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\CompriaxSystem.Domain\CompriaxSystem.Domain.csproj" />
		<ProjectReference Include="..\CompriaxSystem.Application\CompriaxSystem.Application.csproj" />
		<ProjectReference Include="..\CompriaxSystem.Infrastructure\CompriaxSystem.Infrastructure.csproj" />
		<PackageReference Include="mercadopago-sdk" Version="3.7.0" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
	</ItemGroup>

</Project>
